version: "3.9"
services: 
  web:
    image: jesusbarcia/codeurjc-2021-22-daw-webapp4
    restart: always
    ports:
      - 8443:8443      
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/wallypop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallypop
    volumes:
      - ./postgresql:/var/lib/postgresql/data