DROP TABLE IF EXISTS USER;
 
CREATE TABLE USER (
	ID_USER IDENTITY NOT NULL PRIMARY KEY,
	FULL_NAME VARCHAR(250) NOT NULL,
	PASSWORD VARCHAR(256) NOT NULL,
	EMAIL VARCHAR(250) NOT NULL,
	TEL VARCHAR(9) NOT NULL,
	N_SOLD INT DEFAULT 0,
	N_SELL INT DEFAULT 0,
	IS_ADMIN BIT DEFAULT 0
);

DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE ARTICLE (
	ID_ARTICLE INT AUTO_INCREMENT PRIMARY KEY,
	ID_USER INT,
	TITLE VARCHAR(250) NOT NULL,
	DESCRIPTION VARCHAR(MAX),
	PRICE INT NOT NULL,
	RESERVED BIT DEFAULT 0,
	SOLD BIT DEFAULT 0,
	PHOTO BLOB,
	N_VISITED INT DEFAULT 0,
	FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER)
);
 
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
	ID_CATEGORY IDENTITY NOT NULL PRIMARY KEY,
	TITLE VARCHAR(250) NOT NULL,
	DESCRIPTION VARCHAR(MAX),
	PHOTO BLOB
);

DROP TABLE IF EXISTS ARTICLE_CATEGORY;

CREATE TABLE ARTICLE_CATEGORY (
	ID_ARTICLE_CATEGORY IDENTITY NOT NULL PRIMARY KEY,
	ID_ARTICLE INT,
	ID_CATEGORY INT,
	FOREIGN KEY (ID_ARTICLE) REFERENCES ARTICLE(ID_ARTICLE),
	FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
);

DROP TABLE IF EXISTS REPORT;

CREATE TABLE REPORT (
	ID_REPORT IDENTITY NOT NULL PRIMARY KEY,
	ID_ARTICLE INT,
	EMAIL VARCHAR(250) NOT NULL,
	DESCRIPTION VARCHAR(MAX) NOT NULL,
	PROOF BLOB,
	FOREIGN KEY (ID_ARTICLE) REFERENCES ARTICLE(ID_ARTICLE)
);

DROP TABLE IF EXISTS FAVORITES;

CREATE TABLE FAVORITES (
	ID_FAVORITE IDENTITY PRIMARY KEY,
	ID_USER INT,
	ID_ARTICLE INT,
	FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY (ID_ARTICLE) REFERENCES ARTICLE(ID_ARTICLE)
);



INSERT INTO USER ( FULL_NAME , PASSWORD , EMAIL , TEL , IS_ADMIN ) VALUES ('ADMIN', 'ADMIN@ADMIN.COM', '1234', '666666666', 1);
INSERT INTO USER ( FULL_NAME , PASSWORD , EMAIL , TEL ) VALUES ('JESUS', 'J@J.COM', '1234', '666666466');
INSERT INTO ARTICLE ( ID_USER , TITLE , DESCRIPTION , PRICE ) VALUES (2, 'Moto como nueva ', 'Vendo moto utilizada solo fines de semana. Mantenimiento al día', 3500);
INSERT INTO CATEGORY ( TITLE , DESCRIPTION ) VALUES ('MOTOS', 'MOTOCICLETAS');
INSERT INTO CATEGORY ( TITLE , DESCRIPTION ) VALUES ('OCASIÓN', 'POCO USO, MENOS DE 1000KM');
INSERT INTO ARTICLE_CATEGORY ( ID_ARTICLE , ID_CATEGORY ) VALUES (1, 1);
INSERT INTO ARTICLE_CATEGORY ( ID_ARTICLE , ID_CATEGORY ) VALUES (1, 2);
INSERT INTO REPORT ( DESCRIPTION , EMAIL , ID_ARTICLE ) VALUES ('Esa moto me la robaron hace un mes. Adjunto la denuncia', 'j@j.com', 1);
INSERT INTO FAVORITES ( ID_ARTICLE , ID_USER ) VALUES (1, 1);